### ISSUE TITLE
MemoryError: Model buffer memory allocation failed

### ISSUE THREAD

**Issue by QianqianF** [kendryte/canmv#39]
**Describe the bug**
I am trying to deploy a kmodel that's around 1MB to k210 but the model can't be loaded.

**To Reproduce**
```
from maix import KPU
kpu = KPU()
kpu.load("/sd/best_model_float32.kmodel")
```
The kmodel used and the tflite model before conversion are attached

**Expected behavior**
I expect the model to load without an issue given the spec of k210.

**Actual behaviour**
I get one of the two errors
```
MicroPython v1.0.5-5-ge1b2766-dirty on 2023-05-24; CanMV_Board with kendryte-k210
Traceback (most recent call last):
  File "<stdin>", line 164, in <module>
  File "<stdin>", line 64, in main
MemoryError: Model buffer memory allocation failed
```
```
MicroPython v1.0.5-5-ge1b2766-dirty on 2023-05-24; CanMV_Board with kendryte-k210
Traceback (most recent call last):
  File "<stdin>", line 164, in <module>
  File "<stdin>", line 64, in main
OSError: Failed to load model
```

**Please complete the following information**
 - IDE version: v2.9.2-2
 - Firmware version: v1.0.5-5-ge1b2766-dirty
 - Board: SiPEED M1
 - OS: Mac

**Comment by QianqianF** [comment]
[best_model_float32.zip](https://github.com/kendryte/canmv/files/12052242/best_model_float32.zip)

**Comment by Puiching-Memory** [comment]
I had the same problem
